**TASK 1** 

- Compute revenues including tax.
- Compute final revenues after tax and discount.
- Create a Boolean list indicating whether revenue > 100. 
- Create a Boolean list indicating whether revenue is between 100 and 300. 
- Add Markdown explanation: Why do parentheses matter in the formula?

In [19]:
revenues = [120, 250, 80, 310, 95]
tax_rate = 0.18
discount_rate = 0.10

In [20]:
#Revenues including tax
rev_inc_tax = [r*(1+tax_rate) for r in revenues]
print("Revenues with tax:", rev_inc_tax)

Revenues with tax: [141.6, 295.0, 94.39999999999999, 365.79999999999995, 112.1]

In [21]:
#Final revenues after tax and discount
rev_inc_tax_disc = [r*(1+tax_rate)*(1 - discount_rate) for r in revenues]
print("Final revenues:", rev_inc_tax_disc)

Final revenues: [127.44, 265.5, 84.96, 329.21999999999997, 100.89]

In [22]:
#Boolean list indicating whether revenue > 100.
lst = [i>100 for i in revenues]
print("Greater than 100:", lst)

Greater than 100: [True, True, False, True, False]

In [23]:
#Boolean list indicating whether revenue is between 100 and 300. 
between_100_300 = [i>100 and i<300 for i in revenues]
print("Between 100 and 300:", between_100_300)

Between 100 and 300: [True, True, False, False, False]

**Add Markdown explanation: Why do parentheses matter in the formula?**

Because parentheses control the order of operations.

**TASK 2**

- Compute total revenue manually using a loop.
- Compute average revenue.
- Identify the maximum value without using max().
- Count how many values are greater than 150.
- Create a new list of revenues after adding 5% commission.

In [24]:
sales = [120, 250, 80, 310, 95]

In [27]:
#Compute total revenue manually using a loop.
total_revenue = 0
for i in sales:
    total_revenue += i
print(f"total_revenue = {total_revenue}")

total_revenue = 855

In [28]:
#Compute average revenue.
total_revenue = 0
for i in sales:
    total_revenue += i
avg_revenue = total_revenue/len(sales)
print(f"average_revenue = {avg_revenue}")

average_revenue = 171.0

In [29]:
#Identify the maximum value without using max()
max_r = 0
for i in sales:
    if i > max_r:
        max_r = i
print(f"max_revenue = {max_r}")

max_revenue = 310

In [34]:
#Count how many values are greater than 150.
count_greater_150 = sum([count > 150 for count in sales])
print(f"how many values are greater than 150 - {count_greater_150}")

how many values are greater than 150 - 2

In [37]:
# new list of revenues after adding 5% commission
new_lst = [(i * 0.95) for i in sales]
print(f"new list of revenues after adding 5% commission - {new_lst}")

new list of revenues after adding 5% commission - [114.0, 237.5, 76.0, 294.5, 90.25]

**TASK 3**

- “Premium” if revenue > 250
- “Standard” if 100 < revenue ≤ 250
- “Low” otherwise

1. Create a list of segment labels.
2. Count how many customers fall into each segment.
3. Add Markdown explanation: Why does the order of elif statements matter?

In [40]:
# Create a list of segment labels
sales = [120, 250, 80, 310, 95]
segment_labels = []
for i in sales:
    if i > 250:
        segment_labels.append("Premium")
    elif i > 100:
        segment_labels.append("Standard")
    else:
        segment_labels.append("Low")
print(f"list of segment labels - {segment_labels}")

list of segment labels - ['Standard', 'Standard', 'Low', 'Premium', 'Low']

In [42]:
#Count how many customers fall into each segment.
premium_count = segment_labels.count("Premium")
standard_count = segment_labels.count("Standard")
low_count = segment_labels.count("Low")

print("Premium:", premium_count)
print("Standard:", standard_count)
print("Low:", low_count)

Premium: 1
Standard: 2
Low: 2

**Why does the order of elif statements matter?**

The if–elif–else structure is checked from top to bottom.
Python stops checking conditions as soon as one condition is True.

**TASK 4**

- Remove duplicates using a set.
- Convert back to a list.
- Compare lengths before and after deduplication.
- Explain in Markdown why sets are unordered.

In [43]:
customer_ids = [1, 2, 3, 3, 4, 5, 5, 6]

In [45]:
# Remove duplicates using a set
set_customer_ids = set(customer_ids)
print(f"Removed duplicates - {set_customer_ids}")

Removed duplicates - {1, 2, 3, 4, 5, 6}

In [47]:
# Convert back to a list.
conv_lst = list(set_customer_ids)
print(f"Convert back to a list - {conv_lst}")

Convert back to a list - [1, 2, 3, 4, 5, 6]

In [ ]:
# Compare lengths before and after deduplication.

len_with_dupl = len(customer_ids)
len_without_dupl = len(conv_lst)

print(f"len with duplicates - {len_with_dupl},\nlen without duplicates - {len_without_dupl}")

len with duplicates - 8,
len without duplicates - 6

**why sets are unordered?**

Sets are implemented using a hash table.
A hash table:
- Stores elements based on their hash value
- Optimizes fast lookup (O(1) average time complexity)
- Does NOT store elements based on insertion order (in traditional set behavior)        
Because elements are placed according to their hash value in memory, their position depends on:
- The hash function
- Internal memory layout
- Python runtime behavior
Not on the order you inserted them.

**TASK 5**

- Add a new key "segment" based on revenue.
- Update revenue to 300.
- Remove "city".
- Loop over the dictionary and print key-value pairs.
- Add Markdown explanation: Why are dictionaries useful for structured data?

In [68]:
customer = {
    "name": "Anna",
    "revenue": 250,
    "city": "Yerevan"
}

In [69]:
# Add a new key "segment" based on revenue
if customer["revenue"] > 250:
    customer["segment"] = "Premium"
elif customer["revenue"] > 100:
    customer["segment"] = "Standard"
else:
    customer["segment"] = "Low"
print(f"customer with segment column- {customer}")

customer with segment column- {'name': 'Anna', 'revenue': 250, 'city': 'Yerevan', 'segment': 'Standard'}

In [70]:
# Update revenue to 300
customer["revenue"] = 300
print(f"updated customer dictionary- {customer}")

updated customer dictionary- {'name': 'Anna', 'revenue': 300, 'city': 'Yerevan', 'segment': 'Standard'}

In [71]:
# Remove "city" 

removed_value = customer.pop("city", None)
print(f"Removed data: {removed_value}")
print(f"Updated dictionary - {customer}")

Removed data: Yerevan
Updated dictionary - {'name': 'Anna', 'revenue': 300, 'segment': 'Standard'}

In [72]:
# Loop over the dictionary and print key-value pairs.
for key, value in customer.items():
    print(f"key, value - {key, value}")

key, value - ('name', 'Anna')
key, value - ('revenue', 300)
key, value - ('segment', 'Standard')

**Why are dictionaries useful for structured data?**

Dictionaries are very useful for structured data because they store information in **key–value pairs**.

This makes the data:

- Organized  
- Easy to understand  
- Easy to access  
- Flexible  

**Bad corners**

Dictionaries are powerful and efficient for structured data,
but they:
- Require immutable keys
- Use more memory
- Need careful key handling
- Are not ideal for ordered or index-based tasks

**TASK 6**

1. Create a list of revenues after 10% tax.
2.  Create a list of revenues greater than 100.
3. Create a list labeling each revenue as:
    - “High” if > 200
    - “Normal” otherwise
4. Compare list comprehension vs loop in Markdown.

In [73]:
revenues = [120, 250, 80, 310, 95]

In [76]:
# Create a list of revenues after 10% tax.
revenues_after_tax = [rev_tax * 0.9 for rev_tax in revenues]
print(f"revenues after 10% tax - {revenues_after_tax}")

revenues after 10% tax - [108.0, 225.0, 72.0, 279.0, 85.5]

In [78]:
# Create a list of revenues greater than 100
revenues_greater_100 = [i for i in revenues if i > 100]
print(f"revenues greater than 100 - {revenues_greater_100}")

revenues greater than 100 - [120, 250, 310]

In [80]:
# Create a list labeling each revenue.
labels = []
for i in revenues:
    if i > 200:
        labels.append("High")
    else:
        labels.append("Normal")
print(f"list labeling each revenue - {labels}")

list labeling each revenue - ['Normal', 'High', 'Normal', 'High', 'Normal']

**Compare list comprehension vs loop in Markdown.**

| Feature     | List Comprehension     | For Loop                |
| ----------- | ---------------------- | ----------------------- |
| Code Length | Short                  | Longer                  |
| Readability | Compact                | Clear for complex logic |
| Performance | Slightly Faster        | Slightly Slower         |
| Best For    | Simple transformations | Complex logic           |

**TASK 7**
1. Add column "revenue_after_tax".
2. Add column "segment" using conditional logic.
3. Filter rows where revenue > 100.
4. Remove the "revenue_after_tax" column.
5. Print the shape of the DataFrame.
6. Add Markdown explanation: Why is this easier than manual loops?

In [83]:
import pandas as pd

data = {
    "revenue": revenues
}

df = pd.DataFrame(data)
df

   revenue
0      120
1      250
2       80
3      310
4       95

In [85]:
# Add column "revenue_after_tax"
df["revenue_after_tax"] = revenues_after_tax
df

   revenue  revenue_after_tax
0      120              108.0
1      250              225.0
2       80               72.0
3      310              279.0
4       95               85.5

In [91]:
#Add column "segment" using conditional logic
for j,i in enumerate(df["revenue"]):
    print(i,j)
    if i > 250:
        df.loc[j, "segment"] = "Premium"
    elif i > 100:
        df.loc[j, "segment"]  = "Standard"
    else:
        df.loc[j, "segment"]  = "Low"
df

120 0
250 1
80 2
310 3
95 4

   revenue  revenue_after_tax   segment
0      120              108.0  Standard
1      250              225.0  Standard
2       80               72.0       Low
3      310              279.0   Premium
4       95               85.5       Low

In [ ]:
# Filter rows where revenue > 100.